# DEBUG = False
DEBUG = True
#SQLALCHEMY_DATABASE_URI = 'mysql+cymysql://root:Whathaveyoudone123@192.168.135.134:3306/fisher'
SQLALCHEMY_DATABASE_URI = 'sqlite:///./fisher.db'
SECRET_KEY = 'long long age there was a king he is a motherfucker was and forever are MOTHERFUCKER'
MAIL_SERVER = 'smtp.163.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USE_TSL = False
MAIL_USERNAME = 'kingnlionheart'
MAIL_PASSWORD = 'king5lionheart'
MAIL_SUBJECT_PREFIX = '[我的平凡]'
MAIL_SENDER = '<我曾经穿过人山人海>'
